version: "3.9"
services:
  web:
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    name: server-endpoint
