# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Docker image and deploy to Azure Web App

env:
  AZURE_WEBAPP_NAME: KEYBOARDIFY-SERVER

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_KEY }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
          secrets: |
            "APP=${{ secrets.APP }}"
            "PORT=${{ secrets.PORT }}"
            "URL=${{ secrets.URL }}"
            "CLIENT=${{ secrets.CLIENT }}"
            "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}"
            "FIREBASE_PRIVATE_KEY_JSON=${{ secrets.FIREBASE_PRIVATE_KEY_JSON }}"
            "FIREBASE_TYPE=${{ secrets.FIREBASE_TYPE }}"
            "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
            "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}"
            "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}"
            "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}"
            "FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}"
            "FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }}"
            "FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }}"
            "FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}"
            "FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'keyboardify-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0A32004475944F91AD9F608E8837E63D }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
